Python3 fix for plot-vcfstats
Fix for the error:
```
TypeError: 'range' object does not support item assignment
```
in generated `plot.py`.

Fix https://github.com/samtools/bcftools/issues/624 .